update single.yml

diff --git a/.github/workflows/single.yml b/.github/workflows/single.yml
--- a/.github/workflows/single.yml
+++ b/.github/workflows/single.yml
@@ -5,84 +5,133 @@ name: Existing cypress tests
 on: workflow_dispatch
 
 jobs:
-  test1:
-    name: Cypress test
+  install:
+    name: Install NPM and Cypress
     runs-on: ubuntu-22.04
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    # install a specific version of Node using
-    # https://github.com/actions/setup-node
-    - name: Use Node.js v14
-      uses: actions/setup-node@v3
-      with:
-        node-version: 14
+      # install a specific version of Node using
+      # https://github.com/actions/setup-node
+      - name: Use Node.js v14
+        uses: actions/setup-node@v3
+        with:
+          node-version: 14
 
-    # just so we learn about available environment variables GitHub provides
-    - name: Print env variables
-      run: |
-        npm i -g @bahmutov/print-env
-        print-env GITHUB
+      # just so we learn about available environment variables GitHub provides
+      - name: Print CI env variables
+        run: |
+          npm i -g @bahmutov/print-env@2
+          print-env GITHUB BUILD ACTIONS || true
 
-    # Restore the previous NPM modules and Cypress binary archives.
-    # Any updated archives will be saved automatically after the entire
-    # workflow successfully finishes.
-    # See https://github.com/actions/cache
-    - name: Cache node modules
-      uses: actions/cache@v3
-      with:
-        path: ~/.npm
-        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-        restore-keys: |
-          ${{ runner.os }}-node-
+      # Restore the previous NPM modules and Cypress binary archives.
+      # Any updated archives will be saved automatically after the entire
+      # workflow successfully finishes.
+      # See https://github.com/actions/cache
+      # we use exact restore key to avoid NPM module snowballing
+      # https://glebbahmutov.com/blog/do-not-let-npm-cache-snowball/
+      - name: Cache central NPM modules
+        uses: actions/cache@v3
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
 
-    - name: Cache Cypress binary
-      uses: actions/cache@v3
-      with:
-        path: ~/.cache/Cypress
-        key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
-        restore-keys: |
-          cypress-${{ runner.os }}-cypress-
+      # we use the exact restore key to avoid Cypress binary snowballing
+      # https://glebbahmutov.com/blog/do-not-let-cypress-cache-snowball/
+      - name: Cache Cypress binary
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/Cypress
+          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+          restore-keys: |
+            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
 
-    - name: install dependencies and verify Cypress
-      env:
-        # make sure every Cypress install prints minimal information
-        CI: 1
-      # print Cypress and OS info
-      run: |
-        # npm ci
-        npx cypress verify
-        npx cypress info
-        npx cypress version
-        npx cypress version --component package
-        npx cypress version --component binary
-        npx cypress version --component electron
-        npx cypress version --component node
+      # Cache local node_modules to pass to testing jobs
+      - name: Cache local node_modules
+        uses: actions/cache@v3
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-modules-${{ github.ref }}-
 
-    # Starts local server, then runs Cypress tests and records results on the dashboard
-    - name: Cypress tests
-      run: |
-        npm start &
-        npx cypress run --record --parallel --browser chrome --group "Parallel 2x"
-      env:
-        # place your secret record key at
-        # https://github.com/cypress-io/cypress-example-kitchensink/settings/secrets
-        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
-        TERM: xterm
+      - name: install dependencies and verify Cypress
+        env:
+          # make sure every Cypress install prints minimal information
+          CI: 1
+        run: |
+          npm ci
+          npx cypress cache path
+          npx cypress cache list
+          npx cypress verify
+          npx cypress info
 
-    # Save videos and screenshots as test artifacts
-    # https://github.com/actions/upload-artifact
-    - uses: actions/upload-artifact@v3
-      with:
-        name: screenshots
-        path: cypress/screenshots
-        # there might be no screenshots created when:
-        # - there are no test failures
-        # so only upload screenshots if previous step has failed
-        if: failure()
-    # video should always be generated
-    - uses: actions/upload-artifact@v3
-      with:
-        name: videos
-        path: cypress/videos
+  # Duplicate job definitions - GitHub YAML does not support
+  # anchor definitions yet, thus we cannot put same steps into a template object yet
+
+  test1:
+    name: Cypress test
+    needs: install
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v3
+
+      # install a specific version of Node using
+      # https://github.com/actions/setup-node
+      - name: Use Node.js v14
+        uses: actions/setup-node@v3
+        with:
+          node-version: 14
+
+      # Restore just local node_modules and the Cypress binary archives.
+      - name: Cache Cypress binary
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/Cypress
+          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+          restore-keys: |
+            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+
+      - name: Cache local node_modules
+        uses: actions/cache@v3
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-modules-${{ github.ref }}-
+
+      # check the restored Cypress binary
+      - name: Check binary
+        run: |
+          npx cypress cache path
+          npx cypress cache list
+
+      # Starts local server, then runs Cypress tests and records results on the dashboard
+      - name: Cypress tests
+        run: |
+          npm start &
+          npx cypress run --record --parallel --browser chrome --group "Parallel 2x"
+        env:
+          # place your secret record key at
+          # https://github.com/cypress-io/cypress-example-kitchensink/settings/secrets
+          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
+          TERM: xterm
+
+    # # Save videos and screenshots as test artifacts
+    # # https://github.com/actions/upload-artifact
+    # - uses: actions/upload-artifact@v3
+    #   with:
+    #     name: screenshots
+    #     path: cypress/screenshots
+    #     # there might be no screenshots created when:
+    #     # - there are no test failures
+    #     # so only upload screenshots if previous step has failed
+    #     if: failure()
+    # # video should always be generated
+    # - uses: actions/upload-artifact@v3
+    #   with:
+    #     name: videos
+    #     path: cypress/videos
